### ISSUE TITLE
Support Decimal128

### ISSUE THREAD

**Issue by fengjiachun** [GreptimeTeam/greptimedb-ingester-rust#12]
The decimal128 type is a database numeric data type for high precision numbers. It's often used in situations demanding precise decimal calculations like finance applications, accounting systems, or fields needing accurate decimal math.
GreptimeDB now accommodates decimal128. The next step is to make client support for this type at the gRPC protocol level.

GreptimeTeam/greptimedb#2682

**Comment by sunng87** [comment]
Fixed in #13
